# Quick links to the docs:
# - Redwood on Render: https://render.com/docs/deploy-redwood
# - Render's Blueprint spec: https://render.com/docs/yaml-spec

services:
- name: CodeGoat-web
  type: web
  env: static
  buildCommand: corepack enable && yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist

  envVars:
  - key: SKIP_INSTALL_DEPS
    value: true
  - key: NODE_VERSION
    value: 20

  routes:
  - type: rewrite
    source: /.redwood/functions/*
    # Replace `destination` here after your first deploy:
    #
    # ```
    # destination: https://my-redwood-project-api.onrender.com/*
    # ```
    destination: https://codegoat.onrender.com/*
  - type: rewrite
    source: /*
    destination: /200.html

- name: CodeGoat-api
  type: web
  plan: free
  env: node
  region: oregon
  buildCommand: corepack enable && yarn install && yarn rw build api
  startCommand: yarn rw deploy render api

  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: CodeGoat-db
      property: connectionString
  - key: NODE_VERSION
    value: 20

databases:
  - name: CodeGoat-db
    region: oregon
